# Generated by Django 4.2.15 on 2024-09-05 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersattendance',
            name='member',
        ),
        migrations.DeleteModel(
            name='MemberMember',
        ),
        migrations.DeleteModel(
            name='MembersAttendance',
        ),
    ]
