# Generated by Django 5.0.7 on 2024-08-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Student', 'Student'), ('Alumni', 'Alumni')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('batch_year', models.CharField(max_length=10)),
                ('dept_degree', models.CharField(max_length=10)),
                ('reg_num', models.CharField(default='DEFAULT_REG_NUM', max_length=20)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Software Engineering', 'Software Engineering'), ('Information Technology', 'Information Technology')], max_length=50)),
                ('batch', models.CharField(choices=[('SP-25', 'SP-25'), ('FA-25', 'FA-25'), ('SP-24', 'SP-24'), ('FA-24', 'FA-24'), ('FA-23', 'FA-23'), ('SP-23', 'SP-23'), ('FA-22', 'FA-22'), ('SP-22', 'SP-22'), ('FA-21', 'FA-21'), ('SP-21', 'SP-21'), ('FA-20', 'FA-20'), ('SP-20', 'SP-20'), ('FA-19', 'FA-19'), ('SP-19', 'SP-19'), ('FA-18', 'FA-18'), ('SP-18', 'SP-18'), ('FA-17', 'FA-17'), ('SP-17', 'SP-17'), ('FA-16', 'FA-16'), ('SP-16', 'SP-16')], max_length=10)),
                ('address', models.TextField()),
                ('joining_date', models.DateField()),
                ('designation', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('General Secretary', 'General Secretary'), ('Information Secretary', 'Information Secretary'), ('Finance Secretary', 'Finance Secretary'), ('Media Head', 'Media Head'), ('Event Head', 'Event Head'), ('Documentation Head', 'Documentation Head'), ('Member', 'Member')], max_length=50)),
            ],
        ),
    ]
