# Generated by Django 5.0.7 on 2024-08-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='reg_num',
        ),
        migrations.AddField(
            model_name='member',
            name='roll_num',
            field=models.CharField(default='000', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='batch',
            field=models.CharField(choices=[('SP-25', 'SP-25'), ('FA-25', 'FA-25'), ('SP-24', 'SP-24'), ('FA-24', 'FA-24'), ('FA-23', 'FA-23'), ('SP-23', 'SP-23'), ('FA-22', 'FA-22'), ('SP-22', 'SP-22'), ('FA-21', 'FA-21'), ('SP-21', 'SP-21'), ('FA-20', 'FA-20'), ('SP-20', 'SP-20'), ('FA-19', 'FA-19'), ('SP-19', 'SP-19'), ('FA-18', 'FA-18'), ('SP-18', 'SP-18'), ('FA-17', 'FA-17'), ('SP-17', 'SP-17'), ('FA-16', 'FA-16'), ('SP-16', 'SP-16')], default='FA-23', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='batch_year',
            field=models.CharField(default='FA-23', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='cnic',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='dept_degree',
            field=models.CharField(default='BSCS', max_length=10),
        ),
    ]
