# Generated by Django 5.0.7 on 2024-08-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0005_alter_member_cnic_alter_member_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='member',
            name='cnic',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_no',
            field=models.CharField(max_length=11),
        ),
    ]
