# Generated by Django 5.0.7 on 2024-08-06 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0007_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='is_present',
            new_name='absent',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_type',
        ),
        migrations.AddField(
            model_name='attendance',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
