# Generated by Django 4.2.15 on 2024-09-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hiring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cnic', models.CharField(max_length=15)),
                ('phone_no', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('reg_num', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('joining_date', models.DateField()),
                ('is_shortlisted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='reg_num',
            field=models.CharField(max_length=50),
        ),
    ]
