# Generated by Django 4.2.15 on 2024-09-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hiring', '0002_member_memberapplication_is_shortlisted_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
