# Generated by Django 4.2.15 on 2024-09-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_componentissue_delete_issuecomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('micro-controller', 'Micro-Controller'), ('sensor', 'Sensor'), ('soldering', 'Soldering'), ('tools', 'Tools'), ('motor_drivers', 'Motor Drivers'), ('communication_modules', 'Communication Modules'), ('power_and_charging', 'Power and Charging'), ('displays_and_interfaces', 'Displays and Interfaces'), ('wiring_and_connectors', 'Wiring and Connectors'), ('robotics_and_drones', 'Robotics and Drones'), ('miscellaneous', 'Miscellaneous'), ('others', 'Others')], max_length=50),
        ),
    ]
