# Generated by Django 4.2.15 on 2024-09-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=15)),
                ('phone_no', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('reg_num', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('component_name', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
        ),
    ]
