# Generated by Django 4.2.15 on 2024-09-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=15)),
                ('phone_no', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reg_num', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
            ],
        ),
    ]
