# Generated by Django 5.0.7 on 2024-08-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_remove_member_reg_num_member_roll_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cnic',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_no',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('cnic', 'email')},
        ),
    ]
