# Generated by Django 5.0.7 on 2024-08-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0008_rename_is_present_attendance_absent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='type',
            field=models.CharField(default='Regular', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
    ]
