# Generated by Django 4.2.15 on 2024-09-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0010_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='designation',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('General Secretary', 'General Secretary'), ('Information Secretary', 'Information Secretary'), ('Finance Secretary', 'Finance Secretary'), ('Media Head', 'Media Head'), ('Event Head', 'Event Head'), ('Documentation Head', 'Documentation Head'), ('Member', 'Member'), ('Core Member', 'Core Member'), ('Lego Advisor', 'Lego Advisor'), ('Graphic Designer', 'Graphic Designer'), ('Technical Head', 'Technical Head'), ('Assistant Technical Head', 'Assistant Technical Head'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer')], max_length=50),
        ),
    ]
